plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
    id 'jvm-test-suite'
}

base {
    archivesName = 'org.rwtodd.agires'
}

testing {
    suites { 
        test { 
            useJUnitJupiter() 
        }
    }
}

dependencies {
//        testImplementation(platform('org.junit:junit-bom:5.9.1'))
//        testImplementation('org.junit.jupiter:junit-jupiter')
}

